### ISSUE TITLE
[Bug]: 2.26.x 版本开始 AccountManager 被混淆

### ISSUE THREAD

**Issue by omg-xtao** [HolographicHat/GetToken#1]

**Comment by HolographicHat** [comment]
020a790135a1f4d7e70b998e132068995e1ed4bd fixed (Release 2.62.2)

**Comment by omg-xtao** [comment]
https://github.com/HolographicHat/GetToken/blob/be3255f14f51040fcad5ce55df697bbcf9776443/app/src/main/java/hat/holo/token/ModuleMain.kt#L56

`MainUserInfoPage` 同时也被弃用了，改成了 `com.mihoyo.hyperion.user_profile.UserProfileFragment`
