### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by Orion-OvO** [HolographicHat/GetToken#5]
When I click the key button, the application always crashes directly. 
btw, I downloaded and tried it directly within 1 minute of seeing the email. I might be the fastest to provide feedback.

**Comment by Rorshachjoe** [comment]
You're not the only one ,bro. I found the another "app-release" working normally ,while extremely troublesome to install

**Comment by Administrator26st** [comment]
I also encountered the same problem, brothers. The version that does not require root has an icon but crashes when clicked, and the version that requires root does not have an icon after installing getoken

**Comment by Rorshachjoe** [comment]
the "root" version is based on the **lsposed** framework,supporting by **magisk**，maybe you have to install **magisk** and **lsposed** framework before activiting the "root" version.
