### ISSUE TITLE
[Feature Request] Add DeviceFp Dump

### ISSUE THREAD

**Issue by Haocen2004** [HolographicHat/GetToken#6]
basically need dump full request body
validated devicefp to bypass 10035/10041 retcode
call 'getfp' doesn't work, may have some other api to register fp

**Comment by HolographicHat** [comment]
Commit: https://github.com/HolographicHat/GetToken/commit/40717efbf5e447a22e9ada72534578dbd08c9f30

Release: https://github.com/HolographicHat/GetToken/releases/tag/2.74.1

Patched: https://github.com/HolographicHat/GetToken/releases/download/2.74.1/miyoushe-361-lspatched.apk
