### ISSUE TITLE
Device Id 获取错误

### ISSUE THREAD

**Issue by omg-xtao** [HolographicHat/GetToken#7]
device_id 应该为 uuid 形式，现在获取的 roid 没啥大用

DeviceUtils 是混淆类，推荐直接读取 "pre_device.xml" 下的 "device_id"

```kotlin
val preDevice = ctx.getSharedPreferences("pre_device.xml", 0)
id = preDevice.getString("device_id", "").toString()
```

**Comment by HolographicHat** [comment]
Commit: https://github.com/HolographicHat/GetToken/commit/fa691224229fd885964abc0cdb9db530a891fcdf

Release: https://github.com/HolographicHat/GetToken/releases/tag/2.75.1

Patched: https://github.com/HolographicHat/GetToken/releases/download/2.75.1/miyoushe-361-lspatched.apk
